const fs = require("node:fs");
const path = require("node:path");

const {
  withDangerousMod,
  withEntitlementsPlist,
  withXcodeProject,
} = require("expo/config-plugins");

const ENV_BLOCK_START = "# @generated by withoutIosPersonalTeamCapabilities";
const ENV_BLOCK_END = "# @end generated Personal Team build settings";

function withPersonalTeamBuildScriptEnvironment(config) {
  const bundleIdentifier = config.ios?.bundleIdentifier;
  if (!bundleIdentifier) {
    throw new Error("A bundle identifier is required for an iOS Personal Team build.");
  }

  return withDangerousMod(config, [
    "ios",
    (modConfig) => {
      const xcodeEnvPath = path.join(modConfig.modRequest.platformProjectRoot, ".xcode.env");
      const generatedBlock = [
        ENV_BLOCK_START,
        "export T3CODE_IOS_PERSONAL_TEAM=1",
        `export T3CODE_IOS_PERSONAL_TEAM_BUNDLE_ID=${bundleIdentifier}`,
        ENV_BLOCK_END,
      ].join("\n");
      const existing = fs.existsSync(xcodeEnvPath) ? fs.readFileSync(xcodeEnvPath, "utf8") : "";
      const withoutPreviousBlock = existing
        .replace(new RegExp(`${ENV_BLOCK_START}[\\s\\S]*?${ENV_BLOCK_END}\\n?`, "g"), "")
        .trimEnd();

      fs.writeFileSync(
        xcodeEnvPath,
        `${withoutPreviousBlock}${withoutPreviousBlock ? "\n\n" : ""}${generatedBlock}\n`,
      );
      return modConfig;
    },
  ]);
}

function withPersonalTeamBuildEnvironment(config) {
  const bundleIdentifier = config.ios?.bundleIdentifier;
  if (!bundleIdentifier) {
    throw new Error("A bundle identifier is required for an iOS Personal Team build.");
  }

  return withXcodeProject(config, (modConfig) => {
    const buildConfigurations = modConfig.modResults.pbxXCBuildConfigurationSection();
    for (const [key, buildConfiguration] of Object.entries(buildConfigurations)) {
      if (key.endsWith("_comment") || !buildConfiguration?.buildSettings) continue;

      // Keep the Personal Team inputs explicit in every app build
      // configuration. The matching .xcode.env exports above also make them
      // available to Expo's separate Pods-target config generation phase.
      buildConfiguration.buildSettings.T3CODE_IOS_PERSONAL_TEAM = "1";
      buildConfiguration.buildSettings.T3CODE_IOS_PERSONAL_TEAM_BUNDLE_ID = `"${bundleIdentifier}"`;
    }
    return modConfig;
  });
}

module.exports = function withoutIosPersonalTeamCapabilities(config) {
  return withPersonalTeamBuildScriptEnvironment(
    withPersonalTeamBuildEnvironment(
      withEntitlementsPlist(config, (modConfig) => {
        delete modConfig.modResults["aps-environment"];
        delete modConfig.modResults["com.apple.developer.applesignin"];
        delete modConfig.modResults["com.apple.developer.associated-domains"];
        delete modConfig.modResults["com.apple.security.application-groups"];
        return modConfig;
      }),
    ),
  );
};
